"""
app_emr.py — Meridian Health EMR Demo
A fake electronic medical records (EMR) system that wraps the Vasion print
engine, intended for demoing PrinterLogic output to healthcare customers.
Runs on port 5759 and shares settings.json with the Print Job Seeder and the
Apex Industrial ERP Demo.
"""

import os
import sys
import uuid
import random
import tempfile
import threading
import webbrowser
import logging
from datetime import datetime, timedelta
from flask import Flask, render_template, request, jsonify, Response

from print_utils import (
    log, CLOUD_REGIONS, INDUSTRIES, resource_path,
    load_settings, save_settings,
    obfuscate_key, deobfuscate_key, build_onprem_url, get_cloud_base_url,
    fetch_printers_from_api, generate_pdf, generate_random_delay,
    send_single_job, send_single_job_from_buffer, INDUSTRY_PRESETS, USERNAME_PRESETS
)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

app = Flask(__name__, template_folder=resource_path('templates'))
app.config['MAX_CONTENT_LENGTH'] = 100 * 1024 * 1024
app.config['UPLOAD_FOLDER'] = tempfile.mkdtemp()

# All print jobs generated by this demo use healthcare-appropriate documents.
INDUSTRY = 'healthcare'

# ============================================================
# Fake clinical data generators
# ============================================================

PROVIDERS = [
    'Dr. Sarah Johnson', 'Dr. Michael Chen', 'Dr. Jennifer Williams',
    'Dr. David Martinez', 'Dr. Emily Brown', 'Dr. Robert Taylor',
    'Dr. Amanda Garcia', 'Dr. Christopher Lee', 'Dr. Jessica Anderson',
    'Dr. Matthew Wilson', 'Dr. Ashley Thomas', 'Dr. Daniel Jackson',
    'Dr. Stephanie White', 'Dr. Andrew Harris', 'Dr. Nicole Martin',
]

DEPARTMENTS = [
    'Cardiology', 'Emergency', 'Internal Medicine', 'Orthopedics',
    'Pediatrics', 'Radiology', 'Oncology', 'Neurology', 'OB/GYN',
    'Family Medicine', 'Surgery', 'Pulmonology',
]

INSURERS = [
    'Blue Cross Blue Shield', 'UnitedHealthcare', 'Aetna', 'Cigna',
    'Humana', 'Kaiser Permanente', 'Medicare', 'Medicaid',
    'Anthem', 'Centene',
]

PATIENT_NAMES = [
    ('Robert Harrington', 'M'), ('Sandra Kowalski', 'F'),
    ('Marcus Webb', 'M'), ('Jennifer Okafor', 'F'),
    ('David Nguyen', 'M'), ('Catherine Reyes', 'F'),
    ('Thomas Petrov', 'M'), ('Laura Chen', 'F'),
    ('Michael Dubois', 'M'), ('Priya Sharma', 'F'),
    ('Gary Thompson', 'M'), ('Elizabeth Moss', 'F'),
    ('John Ramirez', 'M'), ('Maria Vasquez', 'F'),
    ('Andrew Park', 'M'), ('Karen Mitchell', 'F'),
    ('James Sullivan', 'M'), ('Angela Foster', 'F'),
    ('Brian Coleman', 'M'), ('Rachel Greene', 'F'),
]

ENCOUNTER_TYPES = [
    'Office Visit', 'Emergency', 'Telehealth', 'Inpatient',
    'Surgical', 'Follow-up', 'Wellness Exam',
]

LAB_TESTS = [
    'Complete Blood Count (CBC)', 'Basic Metabolic Panel', 'Lipid Panel',
    'Hemoglobin A1C', 'Thyroid Panel (TSH)', 'Urinalysis',
    'Chest X-Ray', 'MRI Brain', 'CT Abdomen', 'EKG',
    'COVID-19 PCR', 'Liver Function Panel',
]

ENCOUNTER_STATUSES = ['Scheduled', 'In Progress', 'Completed', 'Cancelled']
ORDER_STATUSES = ['Pending', 'Collected', 'Resulted', 'Reviewed']
PRIORITIES = ['Routine', 'STAT']
ENCOUNTER_STATUS_WEIGHTS = [0.30, 0.25, 0.40, 0.05]
ORDER_STATUS_WEIGHTS = [0.20, 0.25, 0.35, 0.20]
PRIORITY_WEIGHTS = [0.80, 0.20]


def _rand_date_offset(min_offset, max_offset):
    """Return a date string offset from today by a random number of days."""
    base = datetime.now()
    offset = random.randint(min_offset, max_offset)
    return (base + timedelta(days=offset)).strftime('%Y-%m-%d')


def _rand_dob():
    """Return a plausible date of birth string."""
    base = datetime.now()
    age_days = random.randint(365 * 1, 365 * 90)
    return (base - timedelta(days=age_days)).strftime('%Y-%m-%d')


def generate_patients(n=20):
    patients = []
    used = set()
    for i in range(n):
        name, gender = PATIENT_NAMES[i % len(PATIENT_NAMES)]
        mrn = f'MRN-{random.randint(100000, 999999)}'
        while mrn in used:
            mrn = f'MRN-{random.randint(100000, 999999)}'
        used.add(mrn)
        patients.append({
            'mrn': mrn,
            'name': name,
            'gender': gender,
            'dob': _rand_dob(),
            'provider': random.choice(PROVIDERS),
            'insurer': random.choice(INSURERS),
            'department': random.choice(DEPARTMENTS),
        })
    return sorted(patients, key=lambda x: x['name'])


def generate_encounters(patients, n=30):
    encounters = []
    for i in range(n):
        patient = random.choice(patients)
        enc_id = f'ENC-{random.randint(70000, 99999)}'
        status = random.choices(ENCOUNTER_STATUSES, weights=ENCOUNTER_STATUS_WEIGHTS)[0]
        encounters.append({
            'id': enc_id,
            'patient': patient['name'],
            'mrn': patient['mrn'],
            'type': random.choice(ENCOUNTER_TYPES),
            'provider': random.choice(PROVIDERS),
            'department': random.choice(DEPARTMENTS),
            'status': status,
            'date': _rand_date_offset(-20, 14),
        })
    return sorted(encounters, key=lambda x: x['id'])


def generate_orders(patients, n=24):
    orders = []
    for i in range(n):
        patient = random.choice(patients)
        order_id = f'ORD-{random.randint(20000, 49999)}'
        status = random.choices(ORDER_STATUSES, weights=ORDER_STATUS_WEIGHTS)[0]
        priority = random.choices(PRIORITIES, weights=PRIORITY_WEIGHTS)[0]
        orders.append({
            'id': order_id,
            'patient': patient['name'],
            'mrn': patient['mrn'],
            'test': random.choice(LAB_TESTS),
            'provider': random.choice(PROVIDERS),
            'priority': priority,
            'status': status,
            'order_date': _rand_date_offset(-30, -1),
            'result_date': _rand_date_offset(0, 7),
        })
    return sorted(orders, key=lambda x: x['id'])


def generate_dashboard_data(patients, encounters, orders):
    active_patients = len(patients)
    open_encounters = sum(1 for e in encounters if e['status'] in ['Scheduled', 'In Progress'])
    avg_wait = random.randint(12, 38)
    docs_today = random.randint(24, 90)

    labels = []
    enc_counts = []
    print_counts = []
    base = datetime.now()
    for d in range(29, -1, -1):
        day = base - timedelta(days=d)
        labels.append(day.strftime('%b %d'))
        enc_counts.append(random.randint(1, 8))
        print_counts.append(random.randint(3, 18))

    recent_activity = []
    combined = (
        [('Encounter', e['id'], e['status'], e['provider']) for e in encounters[:3]] +
        [('Lab Order', o['id'], o['status'], o['provider']) for o in orders[:2]]
    )
    random.shuffle(combined)
    for kind, ref, status, user in combined[:5]:
        recent_activity.append({
            'type': kind,
            'ref': ref,
            'status': status,
            'user': user,
            'time': f'{random.randint(1, 59)} min ago',
        })

    return {
        'kpis': {
            'active_patients': active_patients,
            'open_encounters': open_encounters,
            'avg_wait': avg_wait,
            'docs_today': docs_today,
        },
        'chart_labels': labels,
        'enc_counts': enc_counts,
        'print_counts': print_counts,
        'recent_activity': recent_activity,
    }


# Generate fake data at startup (module level — stable per process)
random.seed(73)
PATIENTS = generate_patients(20)
ENCOUNTERS = generate_encounters(PATIENTS, 30)
ORDERS = generate_orders(PATIENTS, 24)
DASHBOARD = generate_dashboard_data(PATIENTS, ENCOUNTERS, ORDERS)
random.seed()  # Restore true randomness after seeding

# SSE session store
job_sessions = {}

# ============================================================
# Helper: build print URL from settings
# ============================================================

def _get_print_url_and_token():
    """Return (url, bearer_token) from settings, or (None, None)."""
    settings = load_settings()
    dest = settings.get('destination', 'cloud_link')

    if dest == 'on_premise':
        url = build_onprem_url(settings)
        token = settings['on_premise'].get('bearer_token', '')
        if token and not token.startswith('Bearer '):
            token = f'Bearer {token}'
        return url, token
    else:
        region = settings['cloud_link'].get('region', '')
        raw_key = deobfuscate_key(settings['cloud_link'].get('api_key', ''))
        if not region or not raw_key:
            return None, None
        base = get_cloud_base_url(region)
        url = f'{base}/v1/print'
        return url, f'Bearer {raw_key}'


# ============================================================
# Page routes
# ============================================================

@app.route('/')
def dashboard():
    return render_template('emr/dashboard.html',
                           page='dashboard',
                           dashboard=DASHBOARD)


@app.route('/encounters')
def encounters():
    tab = request.args.get('tab', 'encounters')
    return render_template('emr/encounters.html',
                           page='encounters',
                           tab=tab,
                           encounters=ENCOUNTERS,
                           orders=ORDERS)


@app.route('/patients')
def patients():
    patient_encounters = {}
    for enc in ENCOUNTERS:
        patient_encounters.setdefault(enc['patient'], []).append(enc['id'])
    return render_template('emr/patients.html',
                           page='patients',
                           patients=PATIENTS,
                           patient_encounters=patient_encounters)


@app.route('/print-queue')
def print_queue():
    settings = load_settings()
    return render_template('emr/print_queue.html',
                           page='print_queue',
                           settings=settings,
                           cloud_regions=list(CLOUD_REGIONS.keys()))


@app.route('/admin')
def admin():
    settings = load_settings()
    display = {
        'destination': settings.get('destination', 'cloud_link'),
        'cloud_link': {
            'region': settings['cloud_link'].get('region', ''),
            'has_api_key': bool(settings['cloud_link'].get('api_key', ''))
        },
        'on_premise': {
            'server': settings['on_premise'].get('server', ''),
            'protocol': settings['on_premise'].get('protocol', 'https'),
            'port': settings['on_premise'].get('port', '443'),
            'has_token': bool(settings['on_premise'].get('bearer_token', ''))
        },
        'industry_paths': settings.get('industry_paths', {})
    }
    return render_template('emr/admin.html',
                           page='admin',
                           settings=display,
                           cloud_regions=list(CLOUD_REGIONS.keys()),
                           industries=INDUSTRIES)


# ============================================================
# API: Settings (shared settings.json)
# ============================================================

@app.route('/api/emr/settings', methods=['GET', 'POST'])
def emr_settings():
    if request.method == 'GET':
        settings = load_settings()
        safe = {
            'cloud_link': {
                'region': settings['cloud_link'].get('region', ''),
                'has_api_key': bool(settings['cloud_link'].get('api_key', ''))
            },
            'on_premise': {
                'server': settings['on_premise'].get('server', ''),
                'protocol': settings['on_premise'].get('protocol', 'https'),
                'port': settings['on_premise'].get('port', '443'),
                'has_token': bool(settings['on_premise'].get('bearer_token', ''))
            },
            'industry_paths': settings.get('industry_paths', {})
        }
        return jsonify(safe)

    data = request.get_json(force=True)
    settings = load_settings()

    if 'destination' in data:
        settings['destination'] = data['destination']

    if 'cloud_link' in data:
        cl = data['cloud_link']
        if 'region' in cl:
            settings['cloud_link']['region'] = cl['region']
        if 'api_key' in cl and cl['api_key']:
            settings['cloud_link']['api_key'] = obfuscate_key(cl['api_key'])

    if 'on_premise' in data:
        op = data['on_premise']
        for field in ['server', 'protocol', 'port']:
            if field in op:
                settings['on_premise'][field] = op[field]
        if 'bearer_token' in op and op['bearer_token']:
            settings['on_premise']['bearer_token'] = op['bearer_token']

    if 'industry_paths' in data:
        for ind, path in data['industry_paths'].items():
            settings['industry_paths'][ind] = path

    if save_settings(settings):
        return jsonify({'success': True})
    return jsonify({'success': False, 'error': 'Could not save settings'}), 500


# ============================================================
# API: Printers
# ============================================================

@app.route('/api/emr/printers')
def emr_printers():
    settings = load_settings()

    region = settings['cloud_link'].get('region', '')
    raw_key = deobfuscate_key(settings['cloud_link'].get('api_key', ''))
    path_filter = settings.get('industry_paths', {}).get(INDUSTRY, '*Healthcare*')

    if not region or not raw_key:
        return jsonify({'success': False, 'error': 'Cloud Link not configured', 'printers': []})

    base_url = get_cloud_base_url(region)
    printers, error = fetch_printers_from_api(raw_key, base_url, path_filter)

    if error:
        return jsonify({'success': False, 'error': error, 'printers': []})
    return jsonify({'success': True, 'printers': printers})


# ============================================================
# API: Print single document
# ============================================================

@app.route('/api/emr/print-order', methods=['POST'])
def emr_print_order():
    """Print a single clinical document as a healthcare PDF."""
    data = request.get_json(force=True)
    order_id = data.get('order_id', 'ENC-00000')
    printer = data.get('printer', '')
    username = data.get('username', 'emr-system@meridianhealth.org')

    if not printer:
        return jsonify({'success': False, 'error': 'No printer specified'}), 400

    url, token = _get_print_url_and_token()
    if not url:
        return jsonify({'success': False, 'error': 'Print destination not configured'}), 400

    filename = f'{order_id}_Document.pdf'
    buffer = generate_pdf(filename, INDUSTRY, min_pages=1, max_pages=3)
    result = send_single_job_from_buffer(url, token, buffer, filename, username, printer, 1, INDUSTRY)

    return jsonify({
        'success': result['success'],
        'order_id': order_id,
        'status_code': result['status_code'],
        'message': 'Print job sent successfully' if result['success'] else result['response']
    })


# ============================================================
# API: Start / Stop bulk print run (SSE)
# ============================================================

@app.route('/api/emr/start-print-run', methods=['POST'])
def emr_start_print_run():
    """Start a bulk healthcare print run. Returns session_id for SSE stream."""
    num_jobs = int(request.form.get('num_jobs', 10))
    timing_mode = request.form.get('timing_mode', 'random')
    fixed_delay = float(request.form.get('fixed_delay', 1.0))
    min_delay = float(request.form.get('min_delay', 0.5))
    max_delay = float(request.form.get('max_delay', 30.0))

    settings = load_settings()
    destination = settings.get('destination', 'cloud_link')

    # If a specific printer was passed (e.g. from patient/dashboard print buttons), use it directly
    specific_printer = request.form.get('printer', '').strip()
    path_filter = settings.get('industry_paths', {}).get(INDUSTRY, '*Healthcare*')

    if destination == 'on_premise':
        url = build_onprem_url(settings)
        raw_token = settings['on_premise'].get('bearer_token', '')
        bearer_token = f'Bearer {raw_token}' if raw_token and not raw_token.startswith('Bearer ') else raw_token
        if specific_printer:
            printers = [specific_printer]
        else:
            raw_key = deobfuscate_key(settings['cloud_link'].get('api_key', ''))
            region = settings['cloud_link'].get('region', '')
            printers, _ = fetch_printers_from_api(raw_key, get_cloud_base_url(region), path_filter) if (region and raw_key) else ([], None)
    else:
        region = settings['cloud_link'].get('region', '')
        raw_key = deobfuscate_key(settings['cloud_link'].get('api_key', ''))
        if not region or not raw_key:
            return jsonify({'success': False, 'error': 'Cloud Link not configured'}), 400
        base = get_cloud_base_url(region)
        url = f'{base}/v1/print'
        bearer_token = f'Bearer {raw_key}'
        if specific_printer:
            printers = [specific_printer]
        else:
            printers, fetch_error = fetch_printers_from_api(raw_key, base, path_filter)
            if not printers:
                return jsonify({'success': False, 'error': fetch_error or 'No printers found in that folder'}), 400

    if not url:
        return jsonify({'success': False, 'error': 'Print destination not configured'}), 400

    session_id = str(uuid.uuid4())
    job_sessions[session_id] = {
        'status': 'running',
        'results': [],
        'stop_flag': False,
        'total': num_jobs,
        'completed': 0,
        'success_count': 0,
    }

    thread = threading.Thread(
        target=_run_print_jobs,
        args=(session_id, url, bearer_token, num_jobs,
              timing_mode, fixed_delay, min_delay, max_delay, printers),
        daemon=True
    )
    thread.start()
    log(f"EMR print run started: session={session_id}, jobs={num_jobs}, printers={len(printers)}")
    return jsonify({'success': True, 'session_id': session_id, 'printer_count': len(printers)})


def _run_print_jobs(session_id, url, bearer_token, num_jobs,
                    timing_mode, fixed_delay, min_delay, max_delay, printers):
    """Worker thread: sends print jobs and updates session state."""
    import time
    session = job_sessions[session_id]
    filenames = INDUSTRY_PRESETS.get(INDUSTRY, INDUSTRY_PRESETS['healthcare'])
    usernames = USERNAME_PRESETS.get(INDUSTRY, USERNAME_PRESETS['healthcare'])

    for i in range(1, num_jobs + 1):
        if session['stop_flag']:
            break

        filename = filenames[(i - 1) % len(filenames)]
        username = usernames[(i - 1) % len(usernames)]
        printer = printers[(i - 1) % len(printers)]

        buffer = generate_pdf(filename, INDUSTRY, min_pages=1, max_pages=8)
        result = send_single_job_from_buffer(
            url, bearer_token, buffer, filename, username, printer, i, INDUSTRY
        )

        session['results'].append(result)
        session['completed'] = i
        if result['success']:
            session['success_count'] += 1

        if i < num_jobs and not session['stop_flag']:
            delay = generate_random_delay(timing_mode, fixed_delay, min_delay, max_delay)
            time.sleep(delay)

    session['status'] = 'stopped' if session['stop_flag'] else 'complete'
    log(f"EMR print run {session_id}: {session['success_count']}/{session['completed']} succeeded")


@app.route('/api/emr/stream-jobs/<session_id>')
def emr_stream_jobs(session_id):
    """SSE endpoint: streams job results to the browser."""
    import time
    import json as _json

    def generate():
        last_sent = 0
        while True:
            session = job_sessions.get(session_id)
            if not session:
                yield 'data: {"error": "Session not found"}\n\n'
                break

            results = session['results']
            for result in results[last_sent:]:
                yield f'data: {_json.dumps(result)}\n\n'
                last_sent += 1

            if session['status'] in ('complete', 'stopped') and last_sent >= len(results):
                summary = {
                    'type': 'complete',
                    'total': session['completed'],
                    'success': session['success_count'],
                    'status': session['status']
                }
                yield f'data: {_json.dumps(summary)}\n\n'
                break

            time.sleep(0.5)

    return Response(generate(), mimetype='text/event-stream',
                    headers={'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no'})


@app.route('/api/emr/stop-jobs/<session_id>', methods=['POST'])
def emr_stop_jobs(session_id):
    session = job_sessions.get(session_id)
    if session:
        session['stop_flag'] = True
        return jsonify({'success': True})
    return jsonify({'success': False, 'error': 'Session not found'}), 404


@app.route('/api/emr/session-status/<session_id>')
def emr_session_status(session_id):
    session = job_sessions.get(session_id)
    if not session:
        return jsonify({'error': 'Session not found'}), 404
    return jsonify({
        'status': session['status'],
        'completed': session['completed'],
        'total': session['total'],
        'success_count': session['success_count'],
    })


# ============================================================
# API: Presets (for print queue panel)
# ============================================================

@app.route('/api/emr/presets')
def emr_presets():
    return jsonify({
        'filenames': INDUSTRY_PRESETS.get(INDUSTRY, []),
        'usernames': USERNAME_PRESETS.get(INDUSTRY, []),
    })


# ============================================================
# Run
# ============================================================

def run_server(open_browser=False):
    """Start the Meridian Health EMR Demo web server on port 5759.

    Args:
        open_browser: If True, open the default browser to the app after a
            short delay. The launcher opens browsers itself, so this defaults
            to False when invoked from the bundled launcher.
    """
    if open_browser:
        threading.Timer(
            1.5, lambda: webbrowser.open('http://localhost:5759')
        ).start()

    # threaded=True is required so SSE streaming responses don't block other
    # requests; use_reloader=False so this works when run from a thread.
    app.run(debug=False, host='localhost', port=5759,
            threaded=True, use_reloader=False)


if __name__ == '__main__':
    log("Meridian Health EMR Demo starting on port 5759")
    run_server(open_browser=True)
